import { chromium } from '@playwright/test';
const base = process.env.BASE ?? 'http://127.0.0.1:3100';
const out = process.env.OUT ?? 'artifacts';
const headed = process.env.HEADED === '1';
const browser = await chromium.launch({ headless: !headed, args: headed ? ['--ignore-gpu-blocklist'] : ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
page.on('pageerror', (e) => console.log('pageerror', e.message));
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') console.log('console', m.type(), m.text().slice(0, 300)); });
await page.goto(base + '/', { waitUntil: 'networkidle' });
await page.waitForSelector('[data-map-ready="true"]', { timeout: 120000 });
await page.waitForTimeout(3500);
await page.screenshot({ path: `${out}/bto-overview.png` });
console.log('overview done');
const toggle = page.getByRole('button', { name: /Explore sites/ });
if (await toggle.count()) await toggle.first().click();
await page.getByRole('button', { name: 'Tampines Nova', exact: true }).click();
await page.mouse.move(700, 120);
await page.waitForTimeout(3200);
await page.screenshot({ path: `${out}/bto-tampines-focused.png` });
console.log('focused done');
await page.getByRole('button', { name: 'Back to narrowing' }).click();
await page.waitForTimeout(2200);
if (await toggle.count()) await toggle.first().click();
await page.getByRole('button', { name: 'Redhill Peaks', exact: true }).click();
await page.mouse.move(700, 120);
await page.waitForTimeout(3200);
await page.screenshot({ path: `${out}/bto-redhill-focused.png` });
console.log('redhill done');
await page.getByRole('button', { name: 'Back to narrowing' }).click();
await page.waitForTimeout(2000);
await page.getByTestId('custom-pin-action').click();
await page.locator('canvas').click({ position: { x: 760, y: 520 } });
await page.mouse.move(700, 120);
await page.waitForTimeout(1200);
await page.screenshot({ path: `${out}/bto-custom-pin.png` });
console.log('pin done');
await browser.close();
