import { chromium } from '@playwright/test';
const base = process.env.BASE ?? 'http://127.0.0.1:3100';
const browser = await chromium.launch({ headless: false, args: ['--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
await page.goto(base + '/', { waitUntil: 'networkidle' });
const t0 = Date.now();
await page.waitForSelector('[data-map-ready="true"]', { timeout: 120000 });
console.log('quality', await page.getAttribute('[data-testid="map-boundary-state"]', 'data-map-quality'), 'ready after ms', Date.now() - t0);
const measure = async (label, ms = 4000) => {
  const fps = await page.evaluate((ms) => new Promise((resolve) => { let frames = 0; const start = performance.now(); const tick = () => { frames += 1; if (performance.now() - start < ms) requestAnimationFrame(tick); else resolve(frames / ((performance.now() - start) / 1000)); }; requestAnimationFrame(tick); }), ms);
  const mem = await page.evaluate(() => (performance.memory ? Math.round(performance.memory.usedJSHeapSize / 1048576) : null));
  console.log(`${label}: ${fps.toFixed(1)} fps, JS heap ${mem} MB`);
};
await page.waitForTimeout(3000);
await measure('overview idle');
await page.mouse.move(700, 500); await page.mouse.down();
const dragPromise = (async () => { for (let i = 0; i < 40; i += 1) { await page.mouse.move(700 + i * 4, 500 + Math.sin(i / 5) * 30); await page.waitForTimeout(90); } })();
await measure('overview while orbit-dragging', 3500);
await dragPromise; await page.mouse.up();
await page.getByRole('button', { name: /Explore sites/ }).click();
await page.getByRole('button', { name: 'Tampines Nova', exact: true }).click();
await page.mouse.move(700, 120);
await page.waitForTimeout(2500);
await measure('focused idle');
await page.mouse.move(700, 500); await page.mouse.down();
const dragPromise2 = (async () => { for (let i = 0; i < 40; i += 1) { await page.mouse.move(700 + i * 4, 500 + Math.sin(i / 5) * 30); await page.waitForTimeout(90); } })();
await measure('focused while orbit-dragging', 3500);
await dragPromise2; await page.mouse.up();
const transfer = await page.evaluate(() => performance.getEntriesByType('resource').filter((r) => r.name.includes('/map/')).map((r) => `${r.name.split('/').pop()} ${Math.round(r.transferSize / 1024)}KB`).join(', '));
console.log('map asset transfer:', transfer);
await browser.close();
